### ISSUE TITLE
&pool bug tracking

### ISSUE THREAD

**Issue by Nyhilo** [Nyhilo/Duck-Disciple-Bot#65]
✅ Removing the exact amount for result in a pool drops it to 0, but does not remove it from the pool
✅ Can add 0 of a result to a pool
✅ Can remove results from a pool that don't exist
✅ Typo in error "Pool with that name already existss."
✅ "&pool remove <name>" sends the wrong error message
🟨 Attempting to create a global pool as a non-admin creates a local pool instead
🟥 Escape backticks so that they can be input as expected
✅ Typo in "Successfullly added result to <pool>" 
✅ Server admins are unable to delete global pools (as they should)

Feature request:
⬜ Escape emojis because funny
✅ Pretty up the list of pools, and indicate which ones are global

✅ = Done.
🟨 = Needs testing
🟥 = Won't fix

**Comment by klinkplink** [comment]
Negative list entries cancel out positive list entries

**Comment by Nyhilo** [comment]
Per the global pool bug, will reopen if the issue comes up again.
